version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "adfectus-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xi8nampmqa6y"
s3_prefix = "adfectus-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputBucketName=\"panteras-patterns-audio-analyzer\""
